#!/usr/bin/env python3

import platform
from func.order import getOrderQuestion
from func.random import getRandomQuestion
from func.exam import getExam
from func.error import getError


def main():
    # 根据不同平台使用不同的清屏命令
    if platform.system() == 'Windows':
        clear = 'cls'
    else:
        clear = 'clear'
    pathList = [['./archive/mayuan.json', './archive/mayuan.flag'],
                ['./archive/maogai.json', './archive/maogai.flag']]
    subject = input("请输入刷题科目:1.马原 2.毛概\n")
    if subject == 1:
        path = pathList[0]
    elif subject == 1:
        path = pathList[1]
    else:
        print("输入错误，正在退出……")
        return
    function = input("请输入功能:\n1.顺序刷题\n2.随机刷题\n3.考试模拟\n4.错题本\n")
    if function == 1:
        pass
    elif function == 2:
        pass
    elif function == 3:
        pass
    elif function == 4:
        pass
    else:
        print("输入错误，正在退出……")
        return


if __name__ == "__main__":
    main()
